In [76]:
import os
import numpy as np
from DBI_Base import DBI_Base
from 

idb=DBI_Base("DBI_V1")
period=idb.nptd[idb.nptd>=20180101]
stocks=os.listdir("/mnt/pdata_disk2Tw/RL_data_additional/I_DB/DBI_V1/Data/")
print (np.random.choice(period,1),np.random.choice(stocks,1))

idb.print_DBI(np.random.choice(stocks,1)[0],np.random.choice(period,1)[0])

[20210104] ['SZ000157']
Price_VS_Mount [9.7, 9.78, 9.81, 9.87, 9.95]
Sell_Dan [9.79, 9.784776475856408, 0.45413835908542527, 0.05481816797782314]
Buy_Dan [9.789783333333332, 9.785792037755957, 0.46022819843414503, 0.053751848399325626]
Exchange_Ratios [0.01697812, 0.013874000000000001]
Norm_Average_Nprice_And_Mount_Whole_Day_10M [[9.809999999999999, 73720.0], [9.827602802763495, 1629820.0], [9.877303903422453, 1877455.0], [9.92317685942974, 2755092.0], [9.894939759036145, 1151708.0], [9.875060203093227, 779445.0], [9.84594279496347, 900620.0], [9.838418610185625, 840400.0], [9.830151219432189, 609710.0], [9.828193498787153, 452654.0], [9.854190023752968, 421000.0], [9.849440532081378, 255600.0], [9.82736592968885, 519690.0], [9.808244171534025, 1011158.0], [9.800843218390805, 1087500.0], [9.792490871581407, 1095480.0], [9.790138103604322, 939150.0], [9.786544611360814, 909970.0], [9.78556839491506, 579122.0], [9.769171367719759, 1264433.0], [9.786132616414731, 985700.0], [9.77451992227

In [1]:
from DBTP_Creater import DBTP_Creater
i=DBTP_Creater("DBTP_1M1D")

flag, mess=i.buff.Add("SH600000",20210531)
print(i.buff.Is_Ready())
result_datas = i.create_DBTP_Raw_Data_From_DBI()
HFQ_Ratio = i.buff.get_np_item("HFQ_Ratio", [1])

DBI SH600000 20210531 SuccessAlready Exists
DBI SH600000 20210531 SuccessAlready Exists
DBI SH600000 20210531 SuccessAlready Exists
True


In [22]:
HFQ_Ratio.shape

(1, 1)

In [25]:
result_datas[0].shape

(1, 16)

In [1]:
from DBTP_Creater import DBTP_Creater
i=DBTP_Creater("DBTP_1M1D")
i.DBTP_generator("SH600000",20210531,20210531)

DBI SH600000 20210531 SuccessAlready Exists
DBI SH600000 20210531 SuccessAlready Exists
DBI SH600000 20210531 SuccessAlready Exists
DBTP from DBI SH600000 20210531 success generated


(True, 'Success')

In [2]:
fnwp="/mnt/pdata_disk2Tw/RL_data_additional/TP_DB/DBTP_1M1D/data/SH600000/202105/20210531.pickle"
import pickle
a=pickle.load(open(fnwp,"rb"))

In [4]:
fnwp1="/mnt/pdata_disk2Tw/RL_data_additional/TP_DB/DBTP_10MV1/data/SZ300699/202106/20210601.pickle"
import pickle
b=pickle.load(open(fnwp1,"rb"))


In [15]:
import numpy as np
a=np.array([[[111,112,113],
            [121,122,123]],
           [[211,212,213],
            [221,222,223]]]
           )

In [18]:
a.shape

(2, 2, 3)

In [21]:
a=np.array([[[111],[121],[131],[141],[151],[161],[171]],
           [[211],[221],[231],[241],[251],[261],[271]],
           [[311],[321],[331],[341],[351],[361],[371]],
           [[411],[421],[431],[441],[451],[461],[471]]])

b=np.array([[[1]],
           [[2]],
           [[3]],
           [[4]]])
print(a.shape,b.shape)

a*b


(4, 7, 1) (4, 1, 1)


array([[[ 111],
        [ 121],
        [ 131],
        [ 141],
        [ 151],
        [ 161],
        [ 171]],

       [[ 422],
        [ 442],
        [ 462],
        [ 482],
        [ 502],
        [ 522],
        [ 542]],

       [[ 933],
        [ 963],
        [ 993],
        [1023],
        [1053],
        [1083],
        [1113]],

       [[1644],
        [1684],
        [1724],
        [1764],
        [1804],
        [1844],
        [1884]]])

In [17]:
b=np.array([[[1],[2],[3]]])
a*b

ValueError: operands could not be broadcast together with shapes (2,2,3) (1,3,1) 

#handle lv
#sort lv Nprice Percent Ratio Flag_Tracable
#Nprice Max_min
#percent/Ratio covert category
#Flag_tradable not change

#handle sv
#Nprice Max_min
#volume log / max_min



In [50]:
import numpy as np
import pandas as pd
FT_idx=0
FT_label="LV"
LV_order_TypesD=['NPrice','Ratio','Percent','Flag_Tradable']
assert set(i.FT_TypesD_Flat[FT_idx])==set(LV_order_TypesD)

np_FT_TypesD_Flat_0=np.array(i.FT_TypesD_Flat[FT_idx])
Dict_idxs_LV_TypesD = {v: np.where(np_FT_TypesD_Flat_0 == v)[0].tolist() for v in np.unique(np_FT_TypesD_Flat_0)}
print(Dict_idxs_LV_TypesD)



{'Flag_Tradable': [15], 'NPrice': [0, 1, 2, 3, 4, 5, 6, 9, 10], 'Percent': [7, 8, 11, 12], 'Ratio': [13, 14]}


In [8]:
result_datas[0][0,Dict_idxs_LV_TypesD['NPrice']]

array([10.22      , 10.23      , 10.24      , 10.25      , 10.34      ,
       10.24      , 10.24572039, 10.24      , 10.24367938])

In [51]:
from sklearn.preprocessing import MinMaxScaler

from DBI_Base import hfq_toolbox
iHFQTool=hfq_toolbox()
Hprice=iHFQTool.get_hfqprice_from_Nprice(result_datas[0][0][Dict_idxs_LV_TypesD['NPrice']],HFQ_Ratio[0])
MMScaler = MinMaxScaler(feature_range=(0, 1))
ra=MMScaler.fit_transform(Hprice.reshape(-1,1)).reshape(-1)

In [18]:
Hprice

array([137.105388  , 137.239542  , 137.373696  , 137.50785   ,
       138.715236  , 137.373696  , 137.45043737, 137.373696  ,
       137.42305642])

In [20]:
result_datas[0][0,Dict_idxs_LV_TypesD['Ratio']+Dict_idxs_LV_TypesD['Percent']]

array([0.00126927, 0.001269  , 0.3346553 , 0.22479708, 0.41648207,
       0.20163986])

In [27]:
def convert_ratio_to_category( ratio):
    params = np.array([0, 0.0001, 0.001, 0.005, 0.01, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0])
    assert all((np.roll(params, -1) - params)[:-1])
    assert 2 ** 4 >= len(params)
    return [int(x) for x in list('{0:04b}'.format((params <= ratio).sum() - 1))]


In [52]:
percents=[]
for item in result_datas[0][0,Dict_idxs_LV_TypesD['Ratio']+Dict_idxs_LV_TypesD['Percent']]:
    percents.extend(convert_ratio_to_category(item))
rb=np.array(percents)

In [65]:
#help(np.concatenate)
adj_result=np.concatenate([ra,rb,result_datas[0][0,Dict_idxs_LV_TypesD['Flag_Tradable']]]).reshape((1,-1))
adj_result

array([[0.        , 0.08333333, 0.16666667, 0.25      , 1.        ,
        0.16666667, 0.21433661, 0.16666667, 0.19732821, 0.        ,
        0.        , 1.        , 0.        , 0.        , 0.        ,
        1.        , 0.        , 1.        , 0.        , 0.        ,
        0.        , 0.        , 1.        , 1.        , 1.        ,
        1.        , 0.        , 0.        , 1.        , 0.        ,
        1.        , 1.        , 1.        , 1.        ]])

In [66]:
result_datas[0]=adj_result

In [67]:
result_datas[0]

array([[0.        , 0.08333333, 0.16666667, 0.25      , 1.        ,
        0.16666667, 0.21433661, 0.16666667, 0.19732821, 0.        ,
        0.        , 1.        , 0.        , 0.        , 0.        ,
        1.        , 0.        , 1.        , 0.        , 0.        ,
        0.        , 0.        , 1.        , 1.        , 1.        ,
        1.        , 0.        , 0.        , 1.        , 0.        ,
        1.        , 1.        , 1.        , 1.        ]])

In [75]:
result_datas[1][0][:,0]

array([10.34      , 10.33210754, 10.29898707, 10.29043321, 10.28594713,
       10.28601261, 10.28260168, 10.24923238, 10.24961552, 10.25045362,
       10.24936657, 10.25099669, 10.26338993, 10.25583238, 10.24890789,
       10.24129572, 10.23828089, 10.23177047, 10.24681434, 10.26005775,
       10.24881209, 10.24238907, 10.22938019, 10.23441968, 10.2411317 ,
       10.25488612, 10.26389303, 10.26320755, 10.25125743, 10.25908498,
       10.26138158, 10.2590611 , 10.25291696, 10.24554521, 10.26082474,
       10.2691145 , 10.26688766, 10.27224711, 10.27973649, 10.26683295,
       10.25759605, 10.25858333, 10.25041256, 10.2419633 , 10.24007534,
       10.23590592, 10.23694234, 10.23953878, 10.23648131, 10.23710801,
       10.23929461, 10.2419764 , 10.23180753, 10.23727859, 10.24319382,
       10.23916547, 10.23370986, 10.24019017, 10.24619938, 10.24345396,
       10.24097983, 10.23919763, 10.23004125, 10.23054755, 10.23579885,
       10.22897747, 10.22978073, 10.23225898, 10.23325305, 10.22

In [77]:
result_datas[1][0]
from DBI_Base import hfq_toolbox
iHFQTool=hfq_toolbox()
Hprice=iHFQTool.get_hfqprice_from_Nprice(result_datas[1][0][:,0],HFQ_Ratio[0])
Hprice
MMScaler = MinMaxScaler(feature_range=(0, 1))
ra=MMScaler.fit_transform(Hprice.reshape(-1,1)).reshape(-1)
ra

array([1.        , 0.9337774 , 0.65587627, 0.58410416, 0.5464632 ,
       0.54701262, 0.51839279, 0.23840383, 0.24161864, 0.2486508 ,
       0.23952978, 0.2532075 , 0.35719441, 0.29378186, 0.23568117,
       0.17181034, 0.14651413, 0.09188762, 0.21811499, 0.32923532,
       0.2348773 , 0.18098421, 0.0718317 , 0.11411613, 0.17043418,
       0.28584219, 0.36141574, 0.35566408, 0.2553952 , 0.32107319,
       0.34034308, 0.32087286, 0.26931973, 0.20746616, 0.33567088,
       0.40522708, 0.3865425 , 0.43151157, 0.49435205, 0.38608341,
       0.30858018, 0.31686408, 0.2483063 , 0.17741179, 0.16157063,
       0.12658665, 0.1352828 , 0.15706859, 0.13141452, 0.13667293,
       0.15501979, 0.1775217 , 0.09219858, 0.13810415, 0.18773658,
       0.15393624, 0.10816035, 0.16253416, 0.21295506, 0.18991937,
       0.16915983, 0.1542061 , 0.07737846, 0.08162665, 0.12568828,
       0.06845269, 0.07519252, 0.09598658, 0.10432741, 0.04401265,
       0.1292097 , 0.13029364, 0.09196041, 0.03431803, 0.07399

In [102]:
result_datas[1][0][:,1]
original_data=result_datas[1][0][:,1]

orinal_min=min(original_data[original_data>0])
print (orinal_min,orinal_min//2)
MMScaler = MinMaxScaler(feature_range=(0, 1))
rb=MMScaler.fit_transform(np.log(result_datas[1][0][:,1]+orinal_min//2).reshape(-1,1)).reshape(-1)
rb


11700.0 5850.0


array([0.69225244, 0.73883847, 0.84977841, 0.66375034, 0.63001296,
       0.60807568, 1.        , 0.94935241, 0.83123305, 0.91105129,
       0.7551153 , 0.67979824, 0.63425983, 0.51993097, 0.85993699,
       0.85441103, 0.79819592, 0.84233185, 0.68742824, 0.67639745,
       0.83208338, 0.8506974 , 0.80151093, 0.59141259, 0.53275932,
       0.73178546, 0.50586653, 0.51522054, 0.54613117, 0.66434328,
       0.57927487, 0.59699845, 0.86148851, 0.6527027 , 0.68940023,
       0.59265305, 0.43811044, 0.60255349, 0.61466623, 0.51810179,
       0.73354673, 0.55806074, 0.68117584, 0.63271206, 0.8428201 ,
       0.56896687, 0.59374885, 0.70163852, 0.56084716, 0.51789744,
       0.48732617, 0.59886842, 0.8332713 , 0.67862191, 0.62338135,
       0.48046685, 0.64443885, 0.46377972, 0.46675528, 0.60775269,
       0.48021719, 0.59586071, 0.90817899, 0.63587794, 0.62546959,
       0.588646  , 0.61769657, 0.73185099, 0.75557785, 0.37479182,
       0.65747555, 0.64128356, 0.35398459, 0.89573364, 0.67573

In [88]:
result_datas[1][0][:,1]

array([ 226600.,  291966.,  531467.,  193900.,  161086.,  142700.,
       1188847.,  906700.,  480993.,  738500.,  318900.,  211700.,
        164900.,   87100.,  561300.,  544872.,  402535.,  510600.,
        220711.,  207800.,  483200.,  534100.,  409800.,  130100.,
         93664.,  281000.,   80400.,   84800.,  101000.,  194531.,
        121600.,  134200.,  566000.,  182500.,  223100.,  131000.,
         54300.,  138400.,  148000.,   86200.,  283700.,  108000.,
        213300.,  163500.,  511943.,  114800.,  131800.,  238500.,
        109700.,   86100.,   72300.,  135600.,  486300.,  210343.,
        155300.,   69500.,  174400.,   63100.,   64200.,  142445.,
         69400.,  133355.,  727214.,  166376.,  157100.,  128114.,
        150500.,  281100.,  319700.,   37100.,  187343.,  171400.,
         32600.,  680257.,  207043.,   67700.,   34500.,   93200.,
        107300.,   78700.,   65700.,  204300.,  106100.,  194000.,
         48100.,   72700.,   42200.,   13200.,   38400.,   387

In [96]:
adj_result=np.concatenate([ra.reshape((-1,1)),rb.reshape((-1,1))],axis=1)
adj_result

array([[1.        , 0.70049768],
       [0.9337774 , 0.74590102],
       [0.65587627, 0.85390716],
       [0.58410416, 0.67269938],
       [0.5464632 , 0.63977152],
       [0.54701262, 0.61834469],
       [0.51839279, 1.        ],
       [0.23840383, 0.95075788],
       [0.24161864, 0.83586116],
       [0.2486508 , 0.91351155],
       [0.23952978, 0.7617566 ],
       [0.2532075 , 0.68835307],
       [0.35719441, 0.64391804],
       [0.29378186, 0.5320862 ],
       [0.23568117, 0.86379099],
       [0.17181034, 0.8584146 ],
       [0.14651413, 0.80370566],
       [0.09188762, 0.84666147],
       [0.21811499, 0.69579376],
       [0.32923532, 0.68503626],
       [0.2348773 , 0.83668865],
       [0.18098421, 0.85480133],
       [0.0718317 , 0.8069327 ],
       [0.11411613, 0.60205979],
       [0.17043418, 0.54465952],
       [0.28584219, 0.73902935],
       [0.36141574, 0.51829223],
       [0.35566408, 0.52746745],
       [0.2553952 , 0.55775768],
       [0.32107319, 0.67327785],
       [0.

In [97]:
result_datas[1][0]

array([[1.03400000e+01, 2.26600000e+05],
       [1.03321075e+01, 2.91966000e+05],
       [1.02989871e+01, 5.31467000e+05],
       [1.02904332e+01, 1.93900000e+05],
       [1.02859471e+01, 1.61086000e+05],
       [1.02860126e+01, 1.42700000e+05],
       [1.02826017e+01, 1.18884700e+06],
       [1.02492324e+01, 9.06700000e+05],
       [1.02496155e+01, 4.80993000e+05],
       [1.02504536e+01, 7.38500000e+05],
       [1.02493666e+01, 3.18900000e+05],
       [1.02509967e+01, 2.11700000e+05],
       [1.02633899e+01, 1.64900000e+05],
       [1.02558324e+01, 8.71000000e+04],
       [1.02489079e+01, 5.61300000e+05],
       [1.02412957e+01, 5.44872000e+05],
       [1.02382809e+01, 4.02535000e+05],
       [1.02317705e+01, 5.10600000e+05],
       [1.02468143e+01, 2.20711000e+05],
       [1.02600577e+01, 2.07800000e+05],
       [1.02488121e+01, 4.83200000e+05],
       [1.02423891e+01, 5.34100000e+05],
       [1.02293802e+01, 4.09800000e+05],
       [1.02344197e+01, 1.30100000e+05],
       [1.024113

In [3]:
#fnwp="/mnt/pdata_disk2Tw/RL_data_additional/I_DB/DBI_TradableFlag/Data/SZ002468/201905/20190506.pickle"
fnwp="/mnt/pdata_disk2Tw/RL_data_additional/I_DB/DBI_TradableFlag/Data/SZ002468/201904/20190430.pickle"
import pickle
a=pickle.load(open(fnwp,"rb"))

In [4]:
a

[[True]]

In [6]:
fnwp300="/mnt/data_disk2/n_workspace/data/RL_data/I_DB/Stock_List/Stock300.csv"
fnwp500="/mnt/data_disk2/n_workspace/data/RL_data/I_DB/Stock_List/Stock500.csv"
import pandas as pd

l300=pd.read_csv(fnwp300)["stock"].tolist()
l500=pd.read_csv(fnwp500)["stock"].tolist()

set(l500)&set(l300)

{'SH600038',
 'SH600089',
 'SH600170',
 'SH600188',
 'SH600219',
 'SH600372',
 'SH600398',
 'SH600516',
 'SH600867',
 'SH600928',
 'SH600968',
 'SH601298',
 'SH601828',
 'SH601992',
 'SH601997',
 'SH603260',
 'SZ000709',
 'SZ002468'}

In [1]:
import config as sc
import numpy as np
param_fnwp="/mnt/data_disk2/n_workspace/RL/again_try_resid_lr001_scal20_300_RWR_DBTP_1M1D/config.json"
lc = sc.gconfig()
lc.read_from_json(param_fnwp)
from nets_agent_base import net_agent_base
#(40, 1, 52) (40, 1, 241, 2)
a=np.zeros((40, 1, 52))
b=np.zeros((40, 1, 241, 2))
i=net_agent_base(lc)
m=i.build_predict_model("P")

In [2]:

i.predict([a,b,""])

(array([[0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5]], dtype=float32),
 array([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
 

In [4]:
24*24

576

In [3]:
m.summary()

Model: "P"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
P_input_sv (InputLayer)         [(None, 1, 241, 2)]  0                                            
__________________________________________________________________________________________________
reshape (Reshape)               (None, 241, 2)       0           P_input_sv[0][0]                 
__________________________________________________________________________________________________
Psv0_conv (Conv1D)              (None, 239, 16)      112         reshape[0][0]                    
__________________________________________________________________________________________________
Psv0_pool (MaxPooling1D)        (None, 119, 16)      0           Psv0_conv[0][0]                  
__________________________________________________________________________________________________

In [11]:
import os, json

dnwp="/home/rdchujf/n_workspace/RL"
for dn in os.listdir(dnwp):
    fnwp=os.path.join(dnwp,dn,"config.json")
    a=json.load(open(fnwp,"r"))
    if "Choice_reward_function" in a.keys():
        print (dn)


again_try_resid_lr001_scal20_300_RWR_OneDay_loose_003_C
again_try_resid_lr001_scal20_300_RWR_OneDay_loose_003
